// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using sara_coursework.data;

#nullable disable

namespace sara_coursework.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250519134443_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("sara_coursework.models.Award", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AwardName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("AwardName")
                        .IsUnique();

                    b.ToTable("Awards", (string)null);
                });

            modelBuilder.Entity("sara_coursework.models.AwardAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AwardId")
                        .HasColumnType("int");

                    b.Property<int>("AwardedId")
                        .HasColumnType("int");

                    b.Property<int>("DecreeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AwardId");

                    b.HasIndex("AwardedId");

                    b.HasIndex("DecreeId");

                    b.ToTable("AwardAssignments", (string)null);
                });

            modelBuilder.Entity("sara_coursework.models.AwardReason", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ReasonName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("ReasonName")
                        .IsUnique();

                    b.ToTable("AwardReasons", (string)null);
                });

            modelBuilder.Entity("sara_coursework.models.Awarded", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AwardedType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.HasKey("Id");

                    b.ToTable("Awarded", (string)null);

                    b.HasDiscriminator<string>("AwardedType").HasValue("Awarded");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("sara_coursework.models.Decree", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AwardReasonId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("AwardReasonId");

                    b.HasIndex("Number", "Date")
                        .IsUnique();

                    b.ToTable("Decrees", (string)null);
                });

            modelBuilder.Entity("sara_coursework.models.LogEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Logs", (string)null);
                });

            modelBuilder.Entity("sara_coursework.models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("sara_coursework.models.Citizen", b =>
                {
                    b.HasBaseType("sara_coursework.models.Awarded");

                    b.Property<int?>("CollectiveId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasIndex("CollectiveId");

                    b.HasIndex("LastName", "FirstName", "Position")
                        .IsUnique()
                        .HasFilter("[LastName] IS NOT NULL AND [FirstName] IS NOT NULL AND [Position] IS NOT NULL");

                    b.ToTable("Awarded");

                    b.HasDiscriminator().HasValue("Citizen");
                });

            modelBuilder.Entity("sara_coursework.models.Collective", b =>
                {
                    b.HasBaseType("sara_coursework.models.Awarded");

                    b.Property<string>("CollectiveName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasIndex("CollectiveName")
                        .IsUnique()
                        .HasFilter("[CollectiveName] IS NOT NULL");

                    b.ToTable("Awarded");

                    b.HasDiscriminator().HasValue("Collective");
                });

            modelBuilder.Entity("sara_coursework.models.AwardAssignment", b =>
                {
                    b.HasOne("sara_coursework.models.Award", "Award")
                        .WithMany()
                        .HasForeignKey("AwardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("sara_coursework.models.Awarded", "Awarded")
                        .WithMany("AwardAssignments")
                        .HasForeignKey("AwardedId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("sara_coursework.models.Decree", "Decree")
                        .WithMany("AwardAssignments")
                        .HasForeignKey("DecreeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Award");

                    b.Navigation("Awarded");

                    b.Navigation("Decree");
                });

            modelBuilder.Entity("sara_coursework.models.Decree", b =>
                {
                    b.HasOne("sara_coursework.models.AwardReason", "AwardReason")
                        .WithMany()
                        .HasForeignKey("AwardReasonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AwardReason");
                });

            modelBuilder.Entity("sara_coursework.models.Citizen", b =>
                {
                    b.HasOne("sara_coursework.models.Collective", "Collective")
                        .WithMany("Members")
                        .HasForeignKey("CollectiveId");

                    b.Navigation("Collective");
                });

            modelBuilder.Entity("sara_coursework.models.Awarded", b =>
                {
                    b.Navigation("AwardAssignments");
                });

            modelBuilder.Entity("sara_coursework.models.Decree", b =>
                {
                    b.Navigation("AwardAssignments");
                });

            modelBuilder.Entity("sara_coursework.models.Collective", b =>
                {
                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
